spring:
  application:
    name: devtanush-spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nicholastanui/environment-variable-repo.git
server:
  port: ${port:8888}
